# Generated by Django 5.0.6 on 2024-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=200, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name_kana',
            field=models.CharField(max_length=20, verbose_name='店名かな'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='place',
            field=models.CharField(max_length=20, verbose_name='住所'),
        ),
    ]
