# Generated by Django 5.0.6 on 2024-06-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_shop_description_alter_shop_name_kana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '店舗情報', 'verbose_name_plural': '店舗情報'},
        ),
    ]
