# Generated by Django 5.0.6 on 2024-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_shop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, default='takosan.png', upload_to=''),
        ),
    ]
