# Generated by Django 4.2.13 on 2024-06-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_review_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='crud.shop', verbose_name='店舗'),
        ),
    ]
