# Generated by Django 4.2.13 on 2024-06-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_review_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='closed_friday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_monday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_saturday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_sunday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_thursday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_tuesday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='closed_wednesday',
        ),
    ]
