# Generated by Django 5.0.6 on 2024-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_shop_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='close_time',
            field=models.TimeField(default='22:00', verbose_name='閉店時間'),
        ),
        migrations.AddField(
            model_name='shop',
            name='open_time',
            field=models.TimeField(default='09:00', verbose_name='開店時間'),
        ),
    ]
