# Generated by Django 5.0.6 on 2024-06-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_shop_close_time_shop_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closed_friday',
            field=models.BooleanField(default=False, verbose_name='金曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_monday',
            field=models.BooleanField(default=False, verbose_name='月曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_saturday',
            field=models.BooleanField(default=False, verbose_name='土曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_sunday',
            field=models.BooleanField(default=False, verbose_name='日曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_thursday',
            field=models.BooleanField(default=False, verbose_name='木曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_tuesday',
            field=models.BooleanField(default=False, verbose_name='火曜定休'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closed_wednesday',
            field=models.BooleanField(default=False, verbose_name='水曜定休'),
        ),
    ]
