# Generated by Django 5.0.6 on 2024-06-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_shop_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=20, verbose_name='エリア名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.area', verbose_name='エリア'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, default='takosan.png', upload_to='', verbose_name='画像'),
        ),
    ]
