# Generated by Django 5.0.6 on 2024-06-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_alter_area_name_alter_category_name_alter_shop_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='価格帯名')),
            ],
            options={
                'verbose_name': '価格帯',
                'verbose_name_plural': '価格帯',
            },
        ),
    ]
